name: Sync to Zendesk Staging
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push Theme folder to Staging Branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: theme
          branch: staging
          clean: true